### ISSUE TITLE
Add Persian language support

### ISSUE THREAD

**Issue by alirezaarzehgar** [go-chi/docs#10]
I want to translate and add Persian support to `chi` documentation. Is it possible to merging such a PR on this repository ?
I can maintain documentations for feature changes also.

**Comment by VojtechVitek** [comment]
Hi @alirezaarzehgar,

It doesn't feel like we'd be able to maintain any more languages besides English at this time.

With the AI translations that are available these days, it should be pretty easy to translate the docs on-the-fly.

Thanks for raising this, though :)

Best,
Vojtech
